Vagrant.configure(2) do |config|
  config.vm.define 'sample-docker-moloch' do |box|
      box.vm.box = "ubuntu/xenial64"
      box.vm.hostname = 'moloch'
      box.vm.network :private_network, ip: "192.168.10.12"
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "4096"]
       vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
      config.vm.provision "shell", path: "installDockerundStuff.bash"
  end
end
